admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 0
static_resources:
  listeners:
  - address:
      socket_address:
        address: 127.0.0.1
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_filters:
          - name: pyvoy
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_modules.v3.DynamicModuleFilter
              dynamic_module_config:
                name: pyvoy
              filter_config:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: '{"app": "kitchensink", "interface": "asgi"}'
              filter_name: pyvoy
              terminal_filter: true
          route_config:
            virtual_hosts:
            - domains:
              - '*'
              name: local_service
          stat_prefix: ingress_http
    name: listener

